version: "3.7"
services:
  fintech-mlm-php:
    build:
      args:
        user: joshua
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: fintech-mlm-php-image
    container_name: fintech-mlm-php-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - fintech-mlm

  fintech-mlm-mysql:
    image: mysql:8.0
    container_name: fintech-mlm-db-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - fintech-mlm-db:/var/lib/mysql
    networks:
      - fintech-mlm

  fintech-mlm-nginx:
    image: nginx:alpine
    container_name: fintech-mlm-nginx-container
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - fintech-mlm

networks:
  fintech-mlm:

volumes:
  fintech-mlm-db: